# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sentence.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sentence.proto',
  package='clabel',
  syntax='proto2',
  serialized_pb=_b('\n\x0esentence.proto\x12\x06\x63label\":\n\x08Relation\x12\x0e\n\x06\x66ormat\x18\x01 \x02(\t\x12\x0e\n\x06token1\x18\x02 \x02(\t\x12\x0e\n\x06token2\x18\x03 \x02(\t\"L\n\tPSentence\x12\x0c\n\x04sent\x18\x01 \x02(\t\x12\r\n\x05token\x18\x02 \x03(\t\x12\"\n\x08relation\x18\x03 \x03(\x0b\x32\x10.clabel.Relation')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_RELATION = _descriptor.Descriptor(
  name='Relation',
  full_name='clabel.Relation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='format', full_name='clabel.Relation.format', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='token1', full_name='clabel.Relation.token1', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='token2', full_name='clabel.Relation.token2', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=84,
)


_PSENTENCE = _descriptor.Descriptor(
  name='PSentence',
  full_name='clabel.PSentence',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sent', full_name='clabel.PSentence.sent', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='token', full_name='clabel.PSentence.token', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='relation', full_name='clabel.PSentence.relation', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=162,
)

_PSENTENCE.fields_by_name['relation'].message_type = _RELATION
DESCRIPTOR.message_types_by_name['Relation'] = _RELATION
DESCRIPTOR.message_types_by_name['PSentence'] = _PSENTENCE

Relation = _reflection.GeneratedProtocolMessageType('Relation', (_message.Message,), dict(
  DESCRIPTOR = _RELATION,
  __module__ = 'sentence_pb2'
  # @@protoc_insertion_point(class_scope:clabel.Relation)
  ))
_sym_db.RegisterMessage(Relation)

PSentence = _reflection.GeneratedProtocolMessageType('PSentence', (_message.Message,), dict(
  DESCRIPTOR = _PSENTENCE,
  __module__ = 'sentence_pb2'
  # @@protoc_insertion_point(class_scope:clabel.PSentence)
  ))
_sym_db.RegisterMessage(PSentence)


# @@protoc_insertion_point(module_scope)
